# Generated by Django 4.0 on 2024-02-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='资产名称')),
                ('asset_type', models.CharField(choices=[('computer', '计算机'), ('furniture', '家具'), ('equipment', '设备')], max_length=50, verbose_name='资产类型')),
                ('purchase_date', models.DateField(verbose_name='购买日期')),
                ('cost', models.FloatField(verbose_name='成本')),
                ('supplier_info', models.CharField(max_length=255, verbose_name='供应商信息')),
                ('location', models.CharField(max_length=255, verbose_name='存放位置')),
                ('state', models.CharField(choices=[('in_use', '使用中'), ('maintenance', '维护中'), ('disposed', '处置中')], max_length=50, verbose_name='状态')),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
                'db_table': 'tb_assets',
            },
        ),
    ]
