# Generated by Django 4.0 on 2024-02-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('computer', '计算机'), ('furniture', '家具'), ('equipment', '设备'), ('physical education', '体育设备'), ('electronics', '电子设备'), ('books and materials', '图书资料'), ('office equipment', '办公设备'), ('art and decorations', '艺术品和装饰'), ('vehicles', '交通工具'), ('research equipment', '科研设备'), ('security equipment', '安全设备'), ('it infrastructure', 'IT基础设施')], max_length=50, verbose_name='资产类型'),
        ),
    ]
