# Generated by Django 4.0 on 2024-02-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('computer', '计算机'), ('furniture', '家具'), ('equipment', '设备'), ('physical_education', '体育设备'), ('electronics', '电子设备'), ('books_and_materials', '图书资料'), ('office_equipment', '办公设备'), ('art_and_decorations', '艺术品和装饰'), ('vehicles', '交通工具'), ('research_equipment', '科研设备'), ('security_equipment', '安全设备'), ('it_infrastructure', 'IT基础设施')], max_length=50, verbose_name='资产类型'),
        ),
    ]
