# Generated by Django 5.0 on 2024-02-07 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("asset_summary", "Asset Summary"),
                            ("maintenance_history", "Maintenance History"),
                            ("inventory_status", "Inventory Status"),
                            ("disposal_record", "Disposal Record"),
                        ],
                        max_length=50,
                        verbose_name="报告类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成日期"),
                ),
                (
                    "parameters",
                    models.TextField(
                        blank=True,
                        help_text="JSON格式的报告生成参数",
                        null=True,
                        verbose_name="报告参数",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="生成者",
                    ),
                ),
            ],
            options={
                "verbose_name": "报告",
                "verbose_name_plural": "报告",
            },
        ),
    ]
